source "https://rubygems.org"

gem "jekyll", "~> 4.2.1"
gem "minima", "~> 2.5"

group :jekyll_plugins do
  gem 'jekyll-redirect-from'
end

gem "kramdown-parser-gfm"
gem "webrick"
gem "i18n"

platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", "~> 1.2"
  gem "tzinfo-data"
end

gem "wdm", "~> 0.1.1", :platforms => [:mingw, :x64_mingw, :mswin]
